server:
  port: ${PORT:5050}
spring:
  application:
    name: clients
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka} #      http://user:password@url/eureka
security:
  user:
    password: ${eureka.password}
---
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
    prefer-ip-address: true
    app-group-name: fgsc
    appname: clients
  password: ${USER_PASSWORD:password}